# .github/workflows/discord-notify.yml
name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit info to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
        run: |
          MESSAGE="📦 **New Commit Pushed!**\n Author: ${COMMIT_AUTHOR}\n Message: ${COMMIT_MESSAGE}\n[↗ View Commit](${COMMIT_URL})"
          jq -nc --arg content "$MESSAGE" '{content: $content, flags: 4096}' \
          | curl -H "Content-Type: application/json" \
                 -X POST \
                 -d @- \
                 $DISCORD_WEBHOOK_URL
